import React, { useState, useMemo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { useAppData } from '../context/AppDataContext';
import { COLORS, SIZES } from '../utils/theme';
import {
  formatCurrency,
  calculateTotals,
  generateReportText,
  generateReportFileName,
  getMonthName,
  filterTransactionsByMonth,
  groupByCategory,
} from '../utils/helpers';

const MONTHS = [
  'All', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
];

function SummaryRow({ label, value, color }) {
  return (
    <View style={styles.summaryRow}>
      <Text style={styles.summaryLabel}>{label}</Text>
      <Text style={[styles.summaryValue, color && { color }]}>{value}</Text>
    </View>
  );
}

function CategoryBar({ category, amount, total, type }) {
  const pct = total > 0 ? (amount / total) * 100 : 0;
  const color = type === 'income' ? COLORS.income : COLORS.expense;
  return (
    <View style={styles.catBar}>
      <View style={styles.catBarHeader}>
        <Text style={styles.catBarLabel}>{category}</Text>
        <Text style={[styles.catBarValue, { color }]}>{formatCurrency(amount)}</Text>
      </View>
      <View style={styles.barTrack}>
        <View style={[styles.barFill, { width: `${Math.min(pct, 100)}%`, backgroundColor: color }]} />
      </View>
      <Text style={styles.catBarPct}>{pct.toFixed(1)}%</Text>
    </View>
  );
}

export default function ReportsScreen({ navigation }) {
  const { transactions, members, meetings, fpoInfo } = useAppData();
  const [selectedMonth, setSelectedMonth] = useState(0); // 0 = all
  const [sharing, setSharing] = useState(false);
  const currentYear = new Date().getFullYear();

  const filteredTransactions = useMemo(() => {
    if (selectedMonth === 0) return transactions;
    return filterTransactionsByMonth(transactions, selectedMonth - 1, currentYear);
  }, [transactions, selectedMonth, currentYear]);

  const { totalIncome, totalExpense } = useMemo(
    () => calculateTotals(filteredTransactions),
    [filteredTransactions]
  );
  const netBalance = totalIncome - totalExpense;

  const incomeTransactions = filteredTransactions.filter((t) => t.type === 'income');
  const expenseTransactions = filteredTransactions.filter((t) => t.type === 'expense');

  const incomeByCategory = useMemo(() => groupByCategory(incomeTransactions), [incomeTransactions]);
  const expenseByCategory = useMemo(() => groupByCategory(expenseTransactions), [expenseTransactions]);

  const handleShareReport = async () => {
    setSharing(true);
    try {
      const isAvailable = await Sharing.isAvailableAsync();
      if (!isAvailable) {
        Alert.alert('Error', 'Sharing is not available on this device.');
        return;
      }

      const reportText = generateReportText(
        fpoInfo,
        filteredTransactions,
        members,
        meetings,
        selectedMonth !== 0
          ? { from: `01-${MONTHS[selectedMonth]}-${currentYear}`, to: `${MONTHS[selectedMonth]}-${currentYear}` }
          : null
      );

      const fileName = generateReportFileName(
        fpoInfo.name,
        selectedMonth !== 0 ? MONTHS[selectedMonth] : null,
        currentYear
      );

      const fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, reportText, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: 'Share FPO Report',
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share report: ' + error.message);
    } finally {
      setSharing(false);
    }
  };

  const handleShareSummary = async () => {
    const summaryText = `
📊 *FPO Accounting Report*
Organization: ${fpoInfo.name}
${selectedMonth !== 0 ? `Period: ${MONTHS[selectedMonth]} ${currentYear}` : `Year: ${currentYear}`}

💰 Total Income: ${formatCurrency(totalIncome)}
💸 Total Expense: ${formatCurrency(totalExpense)}
📈 Net Balance: ${formatCurrency(netBalance)}

👥 Total Members: ${members.length}
📅 Total Meetings: ${meetings.length}
🔢 Transactions: ${filteredTransactions.length}

Generated by FPO Accounting Software`.trim();

    try {
      const isAvailable = await Sharing.isAvailableAsync();
      if (!isAvailable) {
        Alert.alert('Report Summary', summaryText);
        return;
      }
      const fileUri = FileSystem.documentDirectory + 'fpo_summary.txt';
      await FileSystem.writeAsStringAsync(fileUri, summaryText);
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: 'Share Summary',
      });
    } catch (error) {
      Alert.alert('Summary', summaryText);
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Month Filter */}
        <View style={styles.monthSection}>
          <Text style={styles.sectionTitle}>Filter by Month</Text>
          <ScrollView horizontal showsHorizontalScrollIndicator={false}>
            <View style={styles.monthRow}>
              {MONTHS.map((m, i) => (
                <TouchableOpacity
                  key={m}
                  style={[styles.monthChip, selectedMonth === i && styles.monthChipActive]}
                  onPress={() => setSelectedMonth(i)}
                >
                  <Text style={[styles.monthText, selectedMonth === i && styles.monthTextActive]}>
                    {m}
                  </Text>
                </TouchableOpacity>
              ))}
            </View>
          </ScrollView>
        </View>

        {/* Financial Summary */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>
            📊 Financial Summary
            {selectedMonth !== 0 ? ` — ${MONTHS[selectedMonth]} ${currentYear}` : ` — ${currentYear}`}
          </Text>
          <SummaryRow label="Total Income" value={formatCurrency(totalIncome)} color={COLORS.income} />
          <View style={styles.divider} />
          <SummaryRow label="Total Expense" value={formatCurrency(totalExpense)} color={COLORS.expense} />
          <View style={styles.divider} />
          <SummaryRow
            label="Net Balance"
            value={formatCurrency(netBalance)}
            color={netBalance >= 0 ? COLORS.income : COLORS.expense}
          />
          <View style={styles.divider} />
          <SummaryRow label="Transactions" value={filteredTransactions.length.toString()} />
        </View>

        {/* Organization Overview */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>🏢 Organization Overview</Text>
          <SummaryRow label="FPO Name" value={fpoInfo.name || 'N/A'} />
          <View style={styles.divider} />
          <SummaryRow label="Total Members" value={members.length.toString()} />
          <View style={styles.divider} />
          <SummaryRow label="Total Meetings" value={meetings.length.toString()} />
        </View>

        {/* Income Breakdown */}
        {Object.keys(incomeByCategory).length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>💰 Income Breakdown</Text>
            {Object.entries(incomeByCategory)
              .sort((a, b) => b[1].total - a[1].total)
              .map(([cat, data]) => (
                <CategoryBar
                  key={cat}
                  category={cat}
                  amount={data.total}
                  total={totalIncome}
                  type="income"
                />
              ))}
          </View>
        )}

        {/* Expense Breakdown */}
        {Object.keys(expenseByCategory).length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>💸 Expense Breakdown</Text>
            {Object.entries(expenseByCategory)
              .sort((a, b) => b[1].total - a[1].total)
              .map(([cat, data]) => (
                <CategoryBar
                  key={cat}
                  category={cat}
                  amount={data.total}
                  total={totalExpense}
                  type="expense"
                />
              ))}
          </View>
        )}

        {/* Share Actions */}
        <View style={styles.shareSection}>
          <Text style={styles.sectionTitle}>Share Report</Text>
          <TouchableOpacity
            style={[styles.shareBtn, styles.fullReportBtn]}
            onPress={handleShareReport}
            disabled={sharing}
          >
            <Text style={styles.shareBtnEmoji}>📄</Text>
            <Text style={styles.shareBtnText}>
              {sharing ? 'Preparing...' : 'Share Full Report (Text)'}
            </Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.shareBtn, styles.summaryBtn]}
            onPress={handleShareSummary}
          >
            <Text style={styles.shareBtnEmoji}>📱</Text>
            <Text style={[styles.shareBtnText, { color: COLORS.primary }]}>
              Share Quick Summary
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.shareBtn, styles.backupBtn]}
            onPress={() => navigation.navigate('Backup')}
          >
            <Text style={styles.shareBtnEmoji}>💾</Text>
            <Text style={[styles.shareBtnText, { color: '#1565C0' }]}>
              Backup & Restore Data
            </Text>
          </TouchableOpacity>
        </View>

        <View style={{ height: 32 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  monthSection: {
    padding: SIZES.md,
    paddingBottom: 0,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: SIZES.sm,
  },
  monthRow: {
    flexDirection: 'row',
    gap: SIZES.xs,
    paddingBottom: SIZES.xs,
  },
  monthChip: {
    paddingHorizontal: SIZES.sm,
    paddingVertical: SIZES.xs,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  monthChipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  monthText: {
    fontSize: 13,
    color: COLORS.text,
    fontWeight: '500',
  },
  monthTextActive: {
    color: COLORS.white,
    fontWeight: '700',
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    margin: SIZES.md,
    marginBottom: 0,
    padding: SIZES.md,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: SIZES.sm,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SIZES.xs,
  },
  summaryLabel: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
  },
  catBar: {
    marginBottom: SIZES.sm,
  },
  catBarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  catBarLabel: {
    fontSize: 13,
    color: COLORS.text,
  },
  catBarValue: {
    fontSize: 13,
    fontWeight: '600',
  },
  barTrack: {
    height: 6,
    backgroundColor: COLORS.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  barFill: {
    height: 6,
    borderRadius: 3,
  },
  catBarPct: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  shareSection: {
    padding: SIZES.md,
    paddingBottom: 0,
  },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    padding: SIZES.md,
    marginBottom: SIZES.sm,
    elevation: 1,
    gap: SIZES.sm,
  },
  fullReportBtn: {
    backgroundColor: COLORS.primary,
  },
  summaryBtn: {
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  backupBtn: {
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: '#1565C0',
  },
  shareBtnEmoji: {
    fontSize: 20,
  },
  shareBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.white,
    flex: 1,
  },
});
